-xzf needs a dash if I'm going to pass other args to tar

diff --git a/scripts/cvmfsexec-osg-wrapper b/scripts/cvmfsexec-osg-wrapper
--- a/scripts/cvmfsexec-osg-wrapper
+++ b/scripts/cvmfsexec-osg-wrapper
@@ -140,7 +140,7 @@ fi
 
 if [[ -n $CVMFSEXEC_TARBALL ]]; then
     # We are given a tarball: use it.  Turn hardlinks into copies since some filesystems don't support hardlinks
-    tar --hard-dereference xzf "$CVMFSEXEC_TARBALL" || fail "Couldn't extract $CVMFSEXEC_TARBALL"
+    tar --hard-dereference -xzf "$CVMFSEXEC_TARBALL" || fail "Couldn't extract $CVMFSEXEC_TARBALL"
     if [[ -d ./cvmfsexec/$distro ]]; then
         cvmfsexec_dir=$workdir/cvmfsexec/$distro
     else
