Download CVMFSEXEC_TARBALL if it's a URL

diff --git a/scripts/cvmfsexec-osg-wrapper b/scripts/cvmfsexec-osg-wrapper
--- a/scripts/cvmfsexec-osg-wrapper
+++ b/scripts/cvmfsexec-osg-wrapper
@@ -121,7 +121,24 @@ trap 'cd "$prevdir"; rm -rf "$workdir"' EXIT
 cd "$workdir" || fail "Couldn't enter work dir $workdir"
 
 # Obtain cvmfsexec and the OSG CVMFS distribution
-if [[ -f $CVMFSEXEC_TARBALL ]]; then
+if [[ $CVMFSEXEC_TARBALL = *://* ]]; then
+    # We are given a URL; download the tarball from there.
+    msg "Downloading $CVMFSEXEC_TARBALL"
+    errmsg="Couldn't download $CVMFSEXEC_TARBALL"
+    newname=cvmfsexec-osg.tar.gz
+    if command -v curl &>/dev/null; then
+        curl -LSso "$newname" "$CVMFSEXEC_TARBALL" || fail "$errmsg"
+    elif command -v wget &>/dev/null; then
+        wget -O "$newname" "$CVMFSEXEC_TARBALL" || fail "$errmsg"
+    elif command -v GET &>/dev/null; then
+        GET "$CVMFSEXEC_TARBALL" > "$newname" || fail "$errmsg"
+    else
+        fail "No program to download $CVMFSEXEC_TARBALL with"
+    fi
+    CVMFSEXEC_TARBALL=$newname
+fi
+
+if [[ -n $CVMFSEXEC_TARBALL ]]; then
     # We are given a tarball: use it
     tar xzf "$CVMFSEXEC_TARBALL" || fail "Couldn't extract $CVMFSEXEC_TARBALL"
     if [[ -d ./cvmfsexec/$distro ]]; then
@@ -130,8 +147,10 @@ if [[ -f $CVMFSEXEC_TARBALL ]]; then
         cvmfsexec_dir=$workdir/cvmfsexec
     fi
 else
-    # Make the CVMFS distribution ourselves because we don't have a tarball
-    git clone https://github.com/cvmfs/cvmfsexec || fail "Error downloading cvmfsexec from GitHub"
+    # Make the CVMFS distribution ourselves because we weren't given a tarball
+    msg "\$CVMFSEXEC_TARBALL not found or not specified"
+    command -v git &>/dev/null || fail "Required command 'git' not found"
+    git clone -c advice.detachedHead=false https://github.com/cvmfs/cvmfsexec || fail "Error downloading cvmfsexec from GitHub"
     cd cvmfsexec
     # Check out latest tagged version. Only git 2.0+ has "git tag --sort"
     version_tags=$(git tag --list 'v*' | sort -V)
